#%RAML 1.0 DataType
description: data type for patents
type: object
properties:
  sysId: string
  Id: string
  category: string
  name: string
  patentName: string
  Description: string
  researchCenter: 
    type: string
    enum:
      - ARC
      - JPL
      - JSC
      - KSC
      - ARC
      - DFRC
      - GSFC
      - MSFC
      - GRC
      - LARC
      - SSC

