#%RAML 1.0
title: techSmthNASA

types:
  Patent:
    !include /Types/Patent.raml

/patents:
  description: get patents
  get:
    queryParameters:
      research:
        type: string
        enum:
          - ARC
          - JPL
          - JSC
          - KSC
          - ARC
          - DFRC
          - GSFC
          - MSFC
          - GRC
          - LARC
          - SSC
        required: false
      category:
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            type: Patent[]
      400:
        body:
          application/json:
            example:
              message: "Bad request"
